### ISSUE TITLE
SocketException during ApplyProvisioningTemplate

### ISSUE THREAD

**Issue by miloszpp** [OfficeDev/PnP-Guidance#142]
I'm getting the following exception during ApplyProvisioning Template:

> Only one usage of each socket address (protocol/network address/port) is normally permitted

In my code I first create the site collection using CreateSiteCollection which goes fine. Next, I call ApplyProvisioningTemplate which throws the exception.

The full stack trace is below:

```
Error when processing request 4d33277a-e0b8-4e7b-9733-66b2839f3896|System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: Only one usage of each socket address (protocol/network address/port) is normally permitted 10.225.8.182:80
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.InternalConnect(EndPoint remoteEP)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.SharePoint.Client.SPWebRequestExecutor.Execute()
   at Microsoft.SharePoint.Client.ClientContext.GetFormDigestInfoPrivate()
   at Microsoft.SharePoint.Client.ClientContext.EnsureFormDigest()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
   at Microsoft.SharePoint.Client.TenantExtensions.CreateSiteCollection(Tenant tenant, SiteEntity properties)
   at Pfa.SharepointProvisioning.Integration.Sharepoint.SharepointConnector.CreateSiteCollection(SiteCollectionCreationInformation information, SharepointInstanceInformation sharepointInstanceInformation) in E:\T\b2\w\29\s\Pfa.SPProvisioning\Pfa.SPProvisioning.Integration.Sharepoint\SharepointConnector.cs:line 51
```

**Comment by miloszpp** [comment]
I've found a solution to this problem - in my local netsh configuration the maximum number of allowed TCP ports was 256 and the provisioning process needed ~300 to finish.

Anyway, it might be a good idea to use TCP ports more sparingly - for example by reusing the HttpClient instances. See: https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
